**aufgabe 1:**
----
Die Grundlagen der Allgemeinen Relativitätstheorie (ART) hatte Albert Einstein am 25. November 1915 der Preussischen Akademie der Wissenschaften vorgetragen.

Eine Vorhersage der ART besagt, dass Lichtstrahlen von Sternen, die sich hinter der Sonne befinden und gerade am Sonnenrand vorbei auf die Erde treffen, eine Winkelablenkung aufgrund der Raumkrümmung erfahren. Aus dieser Winkelablenkung lässt sich dann der Raumkrümmungsparameter γ bestimmen. In der Newton’schen Physik, wo der Raum nicht gekrümmt ist, hat γ den Wert 0. In der ART hat γ den Wert 1. Im Jahre 1975 wurde an 9 Tagen im National Radio Astronomy Observatory (NRAO) in Green Bank aus der Lichtablenkung der Wert von γ ermittelt. Die Werte dieser Messungen finden Sie in der Datei `gamma.txt` auf Ilias.

Geben Sie den relativen Fehler für den Wert von γ der 1975 erhobenen Messreihe an. Beachten Sie die Anzahl signifikanter Stellen und lassen Sie bei der Eingabe das Prozentzeichen weg.

In [15]:
import pandas as pd

data = pd.read_csv("gamma.txt", sep=",", index_col=0)

In [16]:
data.head()

"gamma"
Day              
April 5     1.000
April 6     0.960
April 7     1.020
April 8     1.000
April 9     1.002

In [20]:
x, s_x = data.mean(), data.std()

Relativer Fehler gemaess deffinition:

$ \bar{x_n} +- \frac{s_x}{\sqrt{n}} $

In [25]:
from math import sqrt

(data.std()/sqrt(data.size))/data.mean()

 "gamma"    0.009869
dtype: float64

**aufgabe 3b:**
---

Nach einer Schamanen-Zeremonie mit Ayahuasca sind Sie in einem Anflug von Wahnsinn der festen Ueberzeugung, dass Sie die Wiedergeburt von Isaac Newton sind. Als erstes wollen Sie die ART widerlegen, und zwar zugunsten Ihrer Theorie mit γ=0. Wie lautet die Nullhypothese, wie die Alternativhypothese in Bezug auf den Wert des Raumkrümmungsparameters γ?

Führen Sie einen statistischen t-Test mit Hilfe des 1975 erhobenen Datensatzes durch. Geben Sie den p-Wert des Tests an, und zwar mit 4 Nachkommastellen.

Nullhypothese: $H_0: \mu = γ = 1$

Alternativhypothese: $H_a: \mu < 1$

In [48]:
import scipy.stats as st

st.ttest_1samp(data, popmean=1).pvalue / 2

# oder

st.t.cdf(x=data.mean(), loc=1, scale=data.std()/sqrt(data.size), df=data.size-1)

array([0.15321671])

aufgabe 3c:
---

Geben Sie aufgrund der in der Datei `gamma.txt` enthaltenen Messwerte die obere Intervallgrenze des einseitigen 98%-Vertrauensintervalls für den wahren Wert des Parameters γ an. (Mit 5 Nachkommastellen)

In [41]:
st.norm.interval(alpha=0.98, loc=data.mean(),
scale=data.std()/np.sqrt(data.size))

(array([0.96661915]), array([1.01204751]))

In [51]:
st.t.interval(alpha=0.94, df=data.size-1, loc=data.mean(), scale=data.std())

(array([0.92520941]), array([1.05345726]))

quizfrage 06:
---

In dem auf Ilias abgelegten zip File ist die Datei `Schokolade_Nobelpreis` abgelegt. Diese enthält für 22 Länder die Anzahl Nobelpreise pro 10 Millionen Einwohnern und der Schokoladenkonsum (in Kilogramm) pro Kopf enthalten. Der Korrelationskoeffizient beträgt

In [42]:
schoko = pd.read_csv("Schokolade_Nobelpreis.txt", delim_whitespace=True)

In [43]:
schoko.head()

Country  Nobel Laureates per 10 Million  \
0       Sweden                          30.677   
1  Switzerland                          30.125   
2       Norway                          24.947   
3      Denmark                          24.695   
4      Austria                          24.577   

   Chocolate consumption (kg) per capita  
0                                    4.4  
1                                   10.2  
2                                    9.2  
3                                    7.9  
4                                    8.5

In [45]:
schoko.describe()

Nobel Laureates per 10 Million  Chocolate consumption (kg) per capita
count                       22.000000                              22.000000
mean                        11.565864                               5.395455
std                         10.079406                               3.098306
min                          0.048000                               0.700000
25%                          2.285250                               2.750000
50%                          9.161500                               4.850000
75%                         18.751250                               8.725000
max                         30.677000                              10.200000

In [46]:
schoko.corr()

Nobel Laureates per 10 Million  \
Nobel Laureates per 10 Million                                1.00000   
Chocolate consumption (kg) per capita                         0.75859   

                                       Chocolate consumption (kg) per capita  
Nobel Laureates per 10 Million                                       0.75859  
Chocolate consumption (kg) per capita                                1.00000